create table Principal(
    id int generated by default as identity primary key ,
    name varchar(100) not null ,
    age int check ( age > 18  )
);

create table School(
    id int generated by default as identity primary key ,
    school_number int not null ,
    principal_id int UNIQUE references Principal(id) on DELETE set null
);

INSERT INTO Principal(name, age) VALUES ('Bob', 28);
INSERT INTO Principal(name, age) VALUES ('Tom', 35);
INSERT INTO Principal(name, age) VALUES ('Katy', 39);
INSERT INTO Principal(name, age) VALUES ('Alice', 45);

INSERT INTO School(school_number, principal_id) VALUES (7, 3);
INSERT INTO School(school_number, principal_id) VALUES (131, 1);
INSERT INTO School(school_number, principal_id) VALUES (18, 2);
INSERT INTO School(school_number, principal_id) VALUES (39, 4);